//=============================================================================
// Copyright (c) 2016-present Allan CORNET (Nelson)
//=============================================================================
// This file is part of the Nelson.
//=============================================================================
// LICENCE_BLOCK_BEGIN
// SPDX-License-Identifier: LGPL-3.0-or-later
// LICENCE_BLOCK_END
//=============================================================================
#pragma once
//=============================================================================
#define GO_PROPERTY_VALUE_ADD_STR L"add"
#define GO_PROPERTY_VALUE_AUTO_STR L"auto"
#define GO_PROPERTY_VALUE_AXES_STR L"axes"
#define GO_PROPERTY_VALUE_BASELINE_STR L"baseline"
#define GO_PROPERTY_VALUE_BOLD_STR L"bold"
#define GO_PROPERTY_VALUE_BOTH_STR L"both"
#define GO_PROPERTY_VALUE_BOTTOM_STR L"bottom"
#define GO_PROPERTY_VALUE_CAP_STR L"cap"
#define GO_PROPERTY_VALUE_CENTER_STR L"center"
#define GO_PROPERTY_VALUE_CENTIMETERS_STR L"centimeters"
#define GO_PROPERTY_VALUE_CHARACTERS_STR L"characters"
#define GO_PROPERTY_VALUE_COLORSPEC_STR L"colorspec"
#define GO_PROPERTY_VALUE_COLUMN_STR L"column"
#define GO_PROPERTY_VALUE_CONTOUR_STR L"contour"
#define GO_PROPERTY_VALUE_DATA_STR L"data"
#define GO_PROPERTY_VALUE_DEMI_STR L"demi"
#define GO_PROPERTY_VALUE_DIAMOND_STR L"diamond"
#define GO_PROPERTY_VALUE_DIRECT_STR L"direct"
#define GO_PROPERTY_VALUE_FIGURE_STR L"figure"
#define GO_PROPERTY_VALUE_FLAT_STR L"flat"
#define GO_PROPERTY_VALUE_GOURAUD_STR L"gouraud"
#define GO_PROPERTY_VALUE_HELVETICA_STR L"helvetica"
#define GO_PROPERTY_VALUE_HEXAGRAM_STR L"hexagram"
#define GO_PROPERTY_VALUE_HGGROUP_STR L"hggroup"
#define GO_PROPERTY_VALUE_IMAGE_STR L"image"
#define GO_PROPERTY_VALUE_IN_STR L"in"
#define GO_PROPERTY_VALUE_INCHES_STR L"inches"
#define GO_PROPERTY_VALUE_INTERP_STR L"interp"
#define GO_PROPERTY_VALUE_ITALIC_STR L"italic"
#define GO_PROPERTY_VALUE_LEFT_STR L"left"
#define GO_PROPERTY_VALUE_LIGHT_STR L"light"
#define GO_PROPERTY_VALUE_LINE_STR L"line"
#define GO_PROPERTY_VALUE_LINEAR_STR L"linear"
#define GO_PROPERTY_VALUE_LIT_STR L"lit"
#define GO_PROPERTY_VALUE_LOG_STR L"log"
#define GO_PROPERTY_VALUE_MANUAL_STR L"manual"
#define GO_PROPERTY_VALUE_MIDDLE_STR L"middle"
#define GO_PROPERTY_VALUE_NONE_STR L"none"
#define GO_PROPERTY_VALUE_NORMAL_STR L"normal"
#define GO_PROPERTY_VALUE_NORMALIZED_STR L"normalized"
#define GO_PROPERTY_VALUE_OBLIQUE_STR L"oblique"
#define GO_PROPERTY_VALUE_OFF_STR L"off"
#define GO_PROPERTY_VALUE_ON_STR L"on"
#define GO_PROPERTY_VALUE_ORTHOGRAPHIC_STR L"orthographic"
#define GO_PROPERTY_VALUE_OUT_STR L"out"
#define GO_PROPERTY_VALUE_OUTERPOSITION_STR L"outerposition"
#define GO_PROPERTY_VALUE_PATCH_STR L"patch"
#define GO_PROPERTY_VALUE_PENTAGRAM_STR L"pentagram"
#define GO_PROPERTY_VALUE_PERSPECTIVE_STR L"perspective"
#define GO_PROPERTY_VALUE_PHONG_STR L"phong"
#define GO_PROPERTY_VALUE_PIXELS_STR L"pixels"
#define GO_PROPERTY_VALUE_POINTS_STR L"points"
#define GO_PROPERTY_VALUE_POSITION_STR L"position"
#define GO_PROPERTY_VALUE_REPLACE_STR L"replace"
#define GO_PROPERTY_VALUE_REPLACECHILDREN_STR L"replacechildren"
#define GO_PROPERTY_VALUE_REVERSE_STR L"reverse"
#define GO_PROPERTY_VALUE_REVERSELIT_STR L"reverselit"
#define GO_PROPERTY_VALUE_RIGHT_STR L"right"
#define GO_PROPERTY_VALUE_ROW_STR L"row"
#define GO_PROPERTY_VALUE_SCALAR_STR L"scalar"
#define GO_PROPERTY_VALUE_SCALED_STR L"scaled"
#define GO_PROPERTY_VALUE_SQUARE_STR L"square"
#define GO_PROPERTY_VALUE_TEX_STR L"tex"
#define GO_PROPERTY_VALUE_TEXTUREMAP_STR L"texturemap"
#define GO_PROPERTY_VALUE_TOP_STR L"top"
#define GO_PROPERTY_VALUE_UNLIT_STR L"unlit"
//=============================================================================
