#==============================================================================
# Copyright (c) 2016-present Allan CORNET (Nelson)
#==============================================================================
# This file is part of the Nelson.
#=============================================================================
# LICENCE_BLOCK_BEGIN
# SPDX-License-Identifier: LGPL-3.0-or-later
# LICENCE_BLOCK_END
#==============================================================================
component_depth: 6
languages:
  - cpp
exclude:
  - /modules/slicot/src/c/.*
  - /modules/slicot/builtin/cpp/.*
  - /modules/f2c/src/c/.*
  - /modules/types/src/include/.*
  - /modules/types/src/cpp/.*
  - /modules/random/src/include/.*
  - /modules/sio_client/src/socket_io/.*
  - /modules/file_archiver/src/c/minizip/.*
  - /modules/help_tools/src/c/hoedown/.*
