#==============================================================================
# Copyright (c) 2016-present Allan CORNET (Nelson)
#==============================================================================
# This file is part of Nelson.
#=============================================================================
# LICENCE_BLOCK_BEGIN
# SPDX-License-Identifier: LGPL-3.0-or-later
# LICENCE_BLOCK_END
#==============================================================================
engines:
  rubocop:
    enabled: true
    #checks:
    #  Rubocop/Metrics/ClassLength:
    #    enabled: false
  brakeman:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby:
        - javascript:
ratings:
  paths:
    - app/**
    - lib/**
    - "**.rb"
    - "**.go"
exclude_paths:
  - "modules/qml_engine/examples/"
  - "modules/help_tools/resources/highlight.pack.js"
  - "modules/sio_client/src/socket_io/"
