extraction:
  cpp:
     prepare:
        packages: 
          - libboost-all-dev
          - libslicot-dev
          - "build-essential"
          - "pkg-config"
          - qt5-default
          - qttools5-dev
          - qml-module-qtquick-controls
          - qml-module-qtquick-controls2          
          
     configure:
        command:
        - cmake .
     index:
        build_command:
        - make

path_classifiers:
  library:
    - modules/qml_engine/examples
    - modules/slicot
    - modules/f2c
    - modules/sio_client/src/socket_io
    - modules/string/src/fmt
