extraction:
  cpp:
     prepare:
        packages: 
          - libboost-all-dev
          - qtbase5-dev
          - qtdeclarative5-dev
          - libqt5webkit5-dev
          - libopenmpi-dev;
          - autotools-dev;
          - libtool;
          - automake;
          - openmpi-bin;
          - gettext;
          - pkg-config;
          - libffi-dev;
          - libicu-dev;
          - libxml2-dev;
          - liblapack-dev;
          - liblapacke-dev;
          - fftw3;
          - fftw3-dev;
          - libasound-dev;
          - portaudio19-dev;
          - libsndfile1-dev;
          - libtag1-dev;
          - alsa-utils;
          - libslicot-dev;
          - libsqlite3-dev;
          - libgl-dev;
          - hdf5-tools;
          - zlib1g-dev;
          - libcurl4-openssl-dev;
          - libgit2-dev;
          - libeigen3-dev;
          - libmatio

     configure:
        command:
        - cmake .
     index:
        build_command:
        - make

path_classifiers:
  library:
    - modules/qml_engine/examples
    - modules/slicot
    - modules/f2c
    - modules/sio_client/src/socket_io
