name: nelson
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - cxx-compiler
  # Host dependencies
  - libgfortran
  - mesalib
  - qt-main
  - boost
  - fftw
  - openblas
  - openmpi
  - openmpi-mpicc
  - openmpi-mpicxx
  - libmatio
  - hdf5
  - portaudio
  - libgit2
  - libcurl
  - gettext
  - icu
  - libxml2
  - libxslt
  - libsndfile
  - libffi
  - libzlib
  - giflib
  - libtiff
  - eigen
  - pkg-config
