%=============================================================================
% Copyright (c) 2016-present Allan CORNET (Nelson)
%=============================================================================
% This file is part of Nelson.
%=============================================================================
% LICENCE_BLOCK_BEGIN
% SPDX-License-Identifier: LGPL-3.0-or-later
% LICENCE_BLOCK_END
%=============================================================================
assert_isequal(parsestring(sprintf('classdef MyClass\nend')), 'classdef');
assert_isequal(parsestring(sprintf('classdef (Abstract) MyClass < handle\nend')), 'classdef');
assert_isequal(parsestring(sprintf('classdef\nend')), 'error');
assert_isequal(parsestring(sprintf('classdef MissingEnd\nproperties\n  X\nend')), 'error');
%=============================================================================
assert_isequal(parsestring(sprintf('properties\n  X\nend')), 'error');
assert_isequal(parsestring(sprintf('methods\n  f()\nend')), 'error');
assert_isequal(parsestring(sprintf('events\n  Changed\nend')), 'error');
assert_isequal(parsestring(sprintf('enumeration\n  One\nend')), 'error');
%=============================================================================
nested_function = sprintf(['function y = outer(x)\n', ...
  '  y = inner(x);\n', ...
  '  function z = inner(t)\n', ...
  '    z = t + 1;\n', ...
  '  end\n', ...
  'end']);
assert_isequal(parsestring(nested_function), 'function');
%=============================================================================
script_local_function = sprintf(['x = helper(41);\n', ...
  'function y = helper(x)\n', ...
  '  y = x + 1;\n', ...
  'end']);
assert_isequal(parsestring(script_local_function), 'script');
%=============================================================================
assert_isequal(parsestring('import package.ClassName'), 'script');
assert_isequal(parsestring('import package.*'), 'script');
assert_isequal(parsestring('global X Y'), 'script');
%=============================================================================
persistent_function = sprintf(['function y = counter()\n', ...
  '  persistent n\n', ...
  '  y = 1;\n', ...
  'end']);
assert_isequal(parsestring(persistent_function), 'function');
%=============================================================================
assert_isequal(parsestring(sprintf('spmd\n  x = 1;\nend')), 'error');
%=============================================================================
assert_isequal(parsestring('x = f().Field;'), 'script');
assert_isequal(parsestring('x = f()(1);'), 'script');
assert_isequal(parsestring('x = f(){1};'), 'script');
%=============================================================================
arguments_repeating = sprintf(['function y = f(x)\n', ...
  'arguments (Repeating)\n', ...
  '  x double\n', ...
  'end\n', ...
  'y = x;\n', ...
  'end']);
assert_isequal(parsestring(arguments_repeating), 'function');
%=============================================================================
arguments_namevalue = sprintf(['function y = f(opts)\n', ...
  'arguments\n', ...
  '  opts.Method (1,1) string = "linear"\n', ...
  'end\n', ...
  'y = opts.Method;\n', ...
  'end']);
assert_isequal(parsestring(arguments_namevalue), 'function');
arguments_namevalue_nested = sprintf(['function y = f(opts)\n', ...
  'arguments\n', ...
  '  opts.Inner.Value double = 7\n', ...
  'end\n', ...
  'y = opts.Inner.Value;\n', ...
  'end']);
assert_isequal(parsestring(arguments_namevalue_nested), 'function');
arguments_namevalue_bad_dot = sprintf(['function y = f(opts)\n', ...
  'arguments\n', ...
  '  opts. double = 7\n', ...
  'end\n', ...
  'y = opts;\n', ...
  'end']);
assert_isequal(parsestring(arguments_namevalue_bad_dot), 'error');
%=============================================================================
