%=============================================================================
% Copyright (c) 2016-present Allan CORNET (Nelson)
%=============================================================================
% This file is part of Nelson.
%=============================================================================
% LICENCE_BLOCK_BEGIN
% SPDX-License-Identifier: LGPL-3.0-or-later
% LICENCE_BLOCK_END
%=============================================================================
mixed_script = sprintf(['mixedValue = mixedLocalHelper(41);\n', ...
  'function y = mixedLocalHelper(x)\n', ...
  '  y = x + 1;\n', ...
  'end']);
assert_isequal(parsestring(mixed_script), 'script');
%=============================================================================
non_trailing_local = sprintf(['x = localBeforeRest(1);\n', ...
  'function y = localBeforeRest(x)\n', ...
  '  y = x + 1;\n', ...
  'end\n', ...
  'z = x + 1;']);
assert_isequal(parsestring(non_trailing_local), 'error');
%=============================================================================
local_in_if = sprintf(['if true\n', ...
  '  function y = localInsideIf(x)\n', ...
  '    y = x;\n', ...
  '  end\n', ...
  'end']);
assert_isequal(parsestring(local_in_if), 'error');
%=============================================================================
local_in_for = sprintf(['for k = 1:2\n', ...
  '  function y = localInsideFor(x)\n', ...
  '    y = x + k;\n', ...
  '  end\n', ...
  'end']);
assert_isequal(parsestring(local_in_for), 'error');
%=============================================================================
local_in_while = sprintf(['while false\n', ...
  '  function y = localInsideWhile(x)\n', ...
  '    y = x;\n', ...
  '  end\n', ...
  'end']);
assert_isequal(parsestring(local_in_while), 'error');
%=============================================================================
local_in_switch = sprintf(['switch 1\n', ...
  'case 1\n', ...
  '  function y = localInsideSwitch(x)\n', ...
  '    y = x;\n', ...
  '  end\n', ...
  'end']);
assert_isequal(parsestring(local_in_switch), 'error');
%=============================================================================
local_in_try = sprintf(['try\n', ...
  '  function y = localInsideTry(x)\n', ...
  '    y = x;\n', ...
  '  end\n', ...
  'catch\n', ...
  'end']);
assert_isequal(parsestring(local_in_try), 'error');
%=============================================================================
local_after_function_then_script = sprintf(['x = localBeforeRest(1);\n', ...
  'function y = localBeforeRest(x)\n', ...
  '  y = x + 1;\n', ...
  'end\n', ...
  'function y = secondLocalBeforeRest(x)\n', ...
  '  y = x + 2;\n', ...
  'end\n', ...
  'z = x + 1;']);
assert_isequal(parsestring(local_after_function_then_script), 'error');
%=============================================================================
path_test = [tempdir(), createGUID()];
mkdir(path_test);
filename = [path_test, '/mixed_script_local_test.m'];
filewrite(filename, ["mixedValue = mixedLocalHelper(41);"; ...
  "mixedAgain = mixedSecondLocal(mixedValue);"; ...
  "function y = mixedLocalHelper(x)"; ...
  "  y = x + 1;"; ...
  "end"; ...
  "function y = mixedSecondLocal(x)"; ...
  "  y = x * 2;"; ...
  "end"]);
run(filename);
assert_isequal(mixedValue, 42);
assert_isequal(mixedAgain, 84);
rmdir(path_test, 's');
%=============================================================================
