%=============================================================================
% Copyright (c) 2016-present Allan CORNET (Nelson)
%=============================================================================
% This file is part of Nelson.
%=============================================================================
% LICENCE_BLOCK_BEGIN
% SPDX-License-Identifier: LGPL-3.0-or-later
% LICENCE_BLOCK_END
%=============================================================================
nested_function = sprintf(['function y = nested_parser_case(x)\n', ...
  '  y = nested_helper(x);\n', ...
  '  function z = nested_helper(t)\n', ...
  '    z = t + 1;\n', ...
  '  end\n', ...
  'end']);
assert_isequal(parsestring(nested_function), 'function');
%=============================================================================
nested_comment_function = sprintf(['function y = nested_comment_case(x)\n', ...
  '  %%{\n', ...
  '  function z = not_a_nested_function(t)\n', ...
  '    z = t + 1;\n', ...
  '  end\n', ...
  '  %%}\n', ...
  '  y = x + 1;\n', ...
  'end']);
assert_isequal(parsestring(nested_comment_function), 'function');
%=============================================================================
path_test = [tempdir(), createGUID()];
mkdir(path_test);
filename = [path_test, '/nested_runtime_case.m'];
filewrite(filename, ["function y = nested_runtime_case(x)"; ...
  "  base = 10;"; ...
  "  y = nested_helper(x);"; ...
  "  function z = nested_helper(t)"; ...
  "    z = t + base;"; ...
  "    base = base + 5;"; ...
  "  end"; ...
  "  y = y + base;"; ...
  "end"]);
addpath(path_test);
assert_isequal(nested_runtime_case(2), 27);
rmpath(path_test);
rmdir(path_test, 's');
%=============================================================================
path_test = [tempdir(), createGUID()];
mkdir(path_test);
filename = [path_test, '/nested_closure_factory.m'];
filewrite(filename, ["function h = nested_closure_factory(seed)"; ...
  "  base = seed;"; ...
  "  h = @nested_closure_step;"; ...
  "  function y = nested_closure_step(delta)"; ...
  "    base = base + delta;"; ...
  "    y = base;"; ...
  "  end"; ...
  "end"]);
addpath(path_test);
h1 = nested_closure_factory(10);
h2 = nested_closure_factory(100);
assert_isequal(h1(2), 12);
assert_isequal(h1(3), 15);
assert_isequal(h2(5), 105);
assert_isequal(h1(1), 16);
assert_isequal(func2str(h1), 'nested_closure_step');
rmpath(path_test);
rmdir(path_test, 's');
%=============================================================================
path_test = [tempdir(), createGUID()];
mkdir(path_test);
filename = [path_test, '/nested_late_capture_factory.m'];
filewrite(filename, ["function h = nested_late_capture_factory(seed)"; ...
  "  h = @nested_late_capture_step;"; ...
  "  base = seed;"; ...
  "  function y = nested_late_capture_step(delta)"; ...
  "    base = base + delta;"; ...
  "    y = base;"; ...
  "  end"; ...
  "end"]);
addpath(path_test);
h = nested_late_capture_factory(20);
assert_isequal(h(2), 22);
assert_isequal(h(3), 25);
rmpath(path_test);
rmdir(path_test, 's');
%=============================================================================
path_test = [tempdir(), createGUID()];
mkdir(path_test);
filename = [path_test, '/nested_str2func_closure_factory.m'];
filewrite(filename, ["function h = nested_str2func_closure_factory(seed)"; ...
  "  base = seed;"; ...
  "  h = str2func('nested_str2func_closure_step');"; ...
  "  function y = nested_str2func_closure_step(delta)"; ...
  "    base = base + delta;"; ...
  "    y = base;"; ...
  "  end"; ...
  "end"]);
addpath(path_test);
h = nested_str2func_closure_factory(30);
assert_isequal(h(4), 34);
assert_isequal(h(6), 40);
rmpath(path_test);
rmdir(path_test, 's');
%=============================================================================
path_test = [tempdir(), createGUID()];
mkdir(path_test);
filename = [path_test, '/nested_sibling_case.m'];
filewrite(filename, ["function y = nested_sibling_case(x)"; ...
  "  scale = 3;"; ...
  "  y = nested_sibling_second(nested_sibling_first(x));"; ...
  "  function a = nested_sibling_first(t)"; ...
  "    a = t + scale;"; ...
  "  end"; ...
  "  function b = nested_sibling_second(t)"; ...
  "    b = t * scale;"; ...
  "  end"; ...
  "end"]);
addpath(path_test);
assert_isequal(nested_sibling_case(4), 21);
rmpath(path_test);
rmdir(path_test, 's');
%=============================================================================
path_test = [tempdir(), createGUID()];
mkdir(path_test);
filename = [path_test, '/nested_deeper_case.m'];
filewrite(filename, ["function y = nested_deeper_case(x)"; ...
  "  base = 5;"; ...
  "  y = nested_middle(x);"; ...
  "  function a = nested_middle(t)"; ...
  "    offset = 7;"; ...
  "    a = nested_inner(t);"; ...
  "    function b = nested_inner(v)"; ...
  "      b = v + base + offset;"; ...
  "    end"; ...
  "  end"; ...
  "end"]);
addpath(path_test);
assert_isequal(nested_deeper_case(2), 14);
rmpath(path_test);
rmdir(path_test, 's');
%=============================================================================
