#!/bin/sh
#
#==============================================================================
# Copyright (c) 2016-present Allan CORNET (Nelson)
#==============================================================================
# This file is part of Nelson.
#=============================================================================
# LICENCE_BLOCK_BEGIN
# SPDX-License-Identifier: LGPL-3.0-or-later
# LICENCE_BLOCK_END
#==============================================================================
BRANCH=${1:-master}
docker build --no-cache --build-arg BRANCH_NAME=${BRANCH} -f Dockerfile_Debian -t nelson_debian .
#==============================================================================
#docker run -ti nelson_debian
#==============================================================================
