#==============================================================================
# Copyright (c) 2016-present Allan CORNET (Nelson)
#==============================================================================
# This file is part of Nelson.
#=============================================================================
# LICENCE_BLOCK_BEGIN
# SPDX-License-Identifier: LGPL-3.0-or-later
# LICENCE_BLOCK_END
#==============================================================================

FROM fedora:43
LABEL maintainer="Allan CORNET nelson.numerical.computation@gmail.com"

ARG BRANCH_NAME
RUN echo "Nelson's branch: ${BRANCH_NAME}"

RUN dnf install -y git

RUN git clone https://github.com/nelson-lang/nelson.git
WORKDIR "/nelson"
RUN cd "/nelson" && git checkout ${BRANCH_NAME}

RUN ./tools/install_dependencies/install-fedora.sh

RUN mkdir /home/nelsonuser

RUN groupadd -f -g 999 nelsonuser || groupadd -f nelsonuser && \
    useradd -r -u 999 -g nelsonuser nelsonuser || useradd -r -g nelsonuser nelsonuser

RUN chown -R nelsonuser:nelsonuser /home/nelsonuser

RUN chown -R nelsonuser:nelsonuser /nelson

USER nelsonuser

ENV AUDIODEV null

ENV PATH="/usr/lib64/openmpi/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/lib64/openmpi/lib:${LD_LIBRARY_PATH}"

RUN just config -DCMAKE_BUILD_TYPE=Release .
RUN just build
RUN just get_module_skeleton
RUN just build_help
RUN just minimal_tests
RUN just package
RUN just benchmarks_no_display
RUN just tests_no_display

ENTRYPOINT ["/nelson/bin/linux/nelson-cli"]
