#==============================================================================
# Copyright (c) 2016-present Allan CORNET (Nelson)
#==============================================================================
# This file is part of the Nelson.
#=============================================================================
# LICENCE_BLOCK_BEGIN
# SPDX-License-Identifier: LGPL-3.0-or-later
# LICENCE_BLOCK_END
#==============================================================================

FROM debian:trixie-slim
LABEL maintainer="Allan CORNET nelson.numerical.computation@gmail.com"

ARG BRANCH_NAME
RUN echo "Nelson's branch: ${BRANCH_NAME}"

RUN rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/nelson-lang/nelson.git

WORKDIR "/nelson"
RUN cd "/nelson" && git checkout ${BRANCH_NAME}

RUN echo $(pwd)
RUN ./tools/install_dependencies/install-debian-trixie.sh

RUN mkdir /home/nelsonuser

RUN groupadd -f -g 999 nelsonuser && \
    useradd -r -u 999 -g nelsonuser nelsonuser

RUN chown -R nelsonuser:nelsonuser /home/nelsonuser

RUN chown -R nelsonuser:nelsonuser /nelson

USER nelsonuser

ENV AUDIODEV null

RUN just config -DCMAKE_BUILD_TYPE=Release .
RUN just build
RUN just get_module_skeleton
RUN just buildhelp
RUN just tests_minimal
RUN just package
RUN cmake --build . -- -j $(nproc) benchmark_all_no_display
RUN cmake --build . -- -j $(nproc) tests_all_no_display

ENTRYPOINT ["/nelson/bin/linux/nelson-cli"]
