//=============================================================================
// This file is part of Nelson.
//=============================================================================
// LICENCE_BLOCK_BEGIN
// SPDX-License-Identifier: LGPL-3.0-or-later
// LICENCE_BLOCK_END
//=============================================================================
// Generated by Nelson Interface Generator 1.0.0
//=============================================================================
#include "NelsonGateway.hpp"
#include "slicot_ab01odBuiltin.hpp"
#include "slicot_ab04mdBuiltin.hpp"
#include "slicot_ab07ndBuiltin.hpp"
#include "slicot_ab08ndBuiltin.hpp"
#include "slicot_ag08bdBuiltin.hpp"
#include "slicot_mb02mdBuiltin.hpp"
#include "slicot_mb03odBuiltin.hpp"
#include "slicot_mb03pdBuiltin.hpp"
#include "slicot_mb03rdBuiltin.hpp"
#include "slicot_mb04gdBuiltin.hpp"
#include "slicot_mb04mdBuiltin.hpp"
#include "slicot_mb05odBuiltin.hpp"
#include "slicot_mc01tdBuiltin.hpp"
#include "slicot_sb01bdBuiltin.hpp"
#include "slicot_sb02odBuiltin.hpp"
#include "slicot_sb03mdBuiltin.hpp"
#include "slicot_sb03odBuiltin.hpp"
#include "slicot_sb04mdBuiltin.hpp"
#include "slicot_sb04qdBuiltin.hpp"
#include "slicot_sb10jdBuiltin.hpp"
#include "slicot_sg02adBuiltin.hpp"
#include "slicot_tb01idBuiltin.hpp"
#include "slicot_tg01adBuiltin.hpp"
//=============================================================================
using namespace Nelson;
//=============================================================================
const std::wstring gatewayName = L"slicot";
//=============================================================================
static const nlsGateway gateway[] = {
    { "slicot_sb10jd", (ptrBuiltin)Nelson::SlicotGateway::slicot_sb10jdBuiltin, 7, 5 },
    { "slicot_mb02md", (ptrBuiltin)Nelson::SlicotGateway::slicot_mb02mdBuiltin, 6, 7 },
    { "slicot_sg02ad", (ptrBuiltin)Nelson::SlicotGateway::slicot_sg02adBuiltin, 10, 16 },
    { "slicot_sb04qd", (ptrBuiltin)Nelson::SlicotGateway::slicot_sb04qdBuiltin, 5, 3 },
    { "slicot_sb04md", (ptrBuiltin)Nelson::SlicotGateway::slicot_sb04mdBuiltin, 5, 3 },
    { "slicot_mb03od", (ptrBuiltin)Nelson::SlicotGateway::slicot_mb03odBuiltin, 6, 5 },
    { "slicot_mb03rd", (ptrBuiltin)Nelson::SlicotGateway::slicot_mb03rdBuiltin, 7, 6 },
    { "slicot_mb03pd", (ptrBuiltin)Nelson::SlicotGateway::slicot_mb03pdBuiltin, 6, 5 },
    { "slicot_ab01od", (ptrBuiltin)Nelson::SlicotGateway::slicot_ab01odBuiltin, 8, 10 },
    { "slicot_ab04md", (ptrBuiltin)Nelson::SlicotGateway::slicot_ab04mdBuiltin, 5, 7 },
    { "slicot_ab08nd", (ptrBuiltin)Nelson::SlicotGateway::slicot_ab08ndBuiltin, 11, 9 },
    { "slicot_sb01bd", (ptrBuiltin)Nelson::SlicotGateway::slicot_sb01bdBuiltin, 10, 7 },
    { "slicot_sb03od", (ptrBuiltin)Nelson::SlicotGateway::slicot_sb03odBuiltin, 6, 6 },
    { "slicot_sb03md", (ptrBuiltin)Nelson::SlicotGateway::slicot_sb03mdBuiltin, 8, 7 },
    { "slicot_sb02od", (ptrBuiltin)Nelson::SlicotGateway::slicot_sb02odBuiltin, 9, 13 },
    { "slicot_mb04md", (ptrBuiltin)Nelson::SlicotGateway::slicot_mb04mdBuiltin, 4, 2 },
    { "slicot_ab07nd", (ptrBuiltin)Nelson::SlicotGateway::slicot_ab07ndBuiltin, 6, 4 },
    { "slicot_ab07nd", (ptrBuiltin)Nelson::SlicotGateway::slicot_ab07ndBuiltin, 6, 4 },
    { "slicot_ag08bd", (ptrBuiltin)Nelson::SlicotGateway::slicot_ag08bdBuiltin, 14, 9 },
    { "slicot_tg01ad", (ptrBuiltin)Nelson::SlicotGateway::slicot_tg01adBuiltin, 7, 6 },
    { "slicot_mc01td", (ptrBuiltin)Nelson::SlicotGateway::slicot_mc01tdBuiltin, 5, 3 },
    { "slicot_mb04gd", (ptrBuiltin)Nelson::SlicotGateway::slicot_mb04gdBuiltin, 4, 2 },
    { "slicot_mb05od", (ptrBuiltin)Nelson::SlicotGateway::slicot_mb05odBuiltin, 5, 4 },
    { "slicot_tb01id", (ptrBuiltin)Nelson::SlicotGateway::slicot_tb01idBuiltin, 6, 5 },
};
//=============================================================================
NLSGATEWAYFUNC(gateway)
//=============================================================================
NLSGATEWAYINFO(gateway)
//=============================================================================
NLSGATEWAYREMOVE(gateway)
//=============================================================================
NLSGATEWAYNAME()
//=============================================================================
