//=============================================================================
// This file is part of Nelson.
//=============================================================================
// LICENCE_BLOCK_BEGIN
// SPDX-License-Identifier: LGPL-3.0-or-later
// LICENCE_BLOCK_END
//=============================================================================
// Generated by Nelson Interface Generator 1.0.0
//=============================================================================
#include <algorithm>
#include "slicot_mb03pdBuiltin.hpp"
#include "Error.hpp"
#include "i18n.hpp"
#include "characters_encoding.hpp"
#include "InputOutputArgumentsCheckers.hpp"
//=============================================================================
using namespace Nelson;
//=============================================================================
#ifdef __cplusplus
extern "C"
{
#endif
    extern int
    mb03pd_(const char* JOBRQ, int* M, int* N, double* A, int* LDA, int* JPVT, double* RCOND,
        double* SVLMAX, double* TAU, int* RANK, double* SVAL, double* DWORK, int* INFO);
#ifdef __cplusplus
}
#endif
//=============================================================================
// [A_OUT, JPVT_OUT, TAU, RANK, SVAL, INFO] = slicot_mb03pd(JOBRQ, A_IN, JPVT_IN, RCOND, SVLMAX)
//=============================================================================
ArrayOfVector
Nelson::SlicotGateway::slicot_mb03pdBuiltin(int nLhs, const ArrayOfVector& argIn)
{
    ArrayOfVector retval;
    nargoutcheck(nLhs, 0, 6);
    nargincheck(argIn, 5, 5);
    // INPUT VARIABLES
    ArrayOf JOBRQ = argIn[0];
    Dimensions dimsJOBRQ = JOBRQ.getDimensions();
    std::string JOBRQ_string = JOBRQ.getContentAsCString();
    const char* JOBRQ_ptr = JOBRQ_string.c_str();
    ArrayOf RCOND = argIn[3];
    Dimensions dimsRCOND = RCOND.getDimensions();
    RCOND.promoteType(NLS_DOUBLE);
    double* RCOND_ptr = (double*)RCOND.getDataPointer();
    ArrayOf SVLMAX = argIn[4];
    Dimensions dimsSVLMAX = SVLMAX.getDimensions();
    SVLMAX.promoteType(NLS_DOUBLE);
    double* SVLMAX_ptr = (double*)SVLMAX.getDataPointer();
    // IN/OUT VARIABLES
    ArrayOf A = argIn[1];
    Dimensions dimsA = A.getDimensions();
    A.promoteType(NLS_DOUBLE);
    ArrayOf A_output = A;
    A_output.ensureSingleOwner();
    double* A_output_ptr = (double*)A_output.getDataPointer();
    ArrayOf JPVT = argIn[2];
    Dimensions dimsJPVT = JPVT.getDimensions();
    JPVT.promoteType(NLS_INT32);
    ArrayOf JPVT_output = JPVT;
    JPVT_output.ensureSingleOwner();
    int* JPVT_output_ptr = (int*)JPVT_output.getDataPointer();
    // LOCAL VARIABLES
    ArrayOf M = ArrayOf::int32RowVectorConstructor(1);
    int* M_ptr = (int*)M.getDataPointer();
    M_ptr[0] = (int)A.getRows();
    ArrayOf N = ArrayOf::int32RowVectorConstructor(1);
    int* N_ptr = (int*)N.getDataPointer();
    N_ptr[0] = (int)A.getColumns();
    ArrayOf LDA = ArrayOf::int32RowVectorConstructor(1);
    int* LDA_ptr = (int*)LDA.getDataPointer();
    LDA_ptr[0] = std::max(1, (int)A.getRows());
    ArrayOf DWORK = ArrayOf::doubleMatrix2dConstructor(1, 3 * (int)A.getRows());
    double* DWORK_ptr = (double*)DWORK.getDataPointer();
    // OUTPUT VARIABLES
    ArrayOf TAU_output = ArrayOf::doubleMatrix2dConstructor(
        (indexType)1, (indexType)std::min((int)A.getRows(), (int)A.getColumns()));
    double* TAU_output_ptr = (double*)TAU_output.getDataPointer();
    ArrayOf RANK_output = ArrayOf::int32RowVectorConstructor(1);
    int* RANK_output_ptr = (int*)RANK_output.getDataPointer();
    ArrayOf SVAL_output = ArrayOf::doubleMatrix2dConstructor((indexType)1, (indexType)3);
    double* SVAL_output_ptr = (double*)SVAL_output.getDataPointer();
    ArrayOf INFO_output = ArrayOf::int32RowVectorConstructor(1);
    int* INFO_output_ptr = (int*)INFO_output.getDataPointer();
    // CHECK INPUT VARIABLES DIMENSIONS
    if (!dimsJOBRQ.isScalar()) {
        raiseError2(_E("nelson:validators:mustBeScalarAtPosition"), 1);
    }
    Dimensions dimsA_expected(std::max(1, (int)A.getRows()), (int)A.getColumns());
    if (!dimsA.equals(dimsA_expected)) {
        raiseError2(_E("nelson:validators:mustBeSizeAtPosition"), 2,
            utf8_to_wstring(dimsA_expected.toString()));
    }
    Dimensions dimsJPVT_expected(1, (int)A.getRows());
    if (!dimsJPVT.equals(dimsJPVT_expected)) {
        raiseError2(L"nelson:validators:mustBeSizeAtPosition", 3,
            utf8_to_wstring(dimsJPVT_expected.toString()));
    }
    if (!dimsRCOND.isScalar()) {
        raiseError2(_E("nelson:validators:mustBeScalarAtPosition"), 4);
    }
    if (!dimsSVLMAX.isScalar()) {
        raiseError2(_E("nelson:validators:mustBeScalarAtPosition"), 5);
    }
    // CALL EXTERN FUNCTION
    try {
        mb03pd_(JOBRQ_ptr, M_ptr, N_ptr, A_output_ptr, LDA_ptr, JPVT_output_ptr, RCOND_ptr,
            SVLMAX_ptr, TAU_output_ptr, RANK_output_ptr, SVAL_output_ptr, DWORK_ptr,
            INFO_output_ptr);
    } catch (const std::runtime_error&) {
        raiseError2(_E("nelson:slicot:slicotFuncFails"), L"mb03pd");
    }
    // ASSIGN OUTPUT VARIABLES
    if (nLhs > 0) {
        retval << A_output;
    }
    if (nLhs > 1) {
        retval << JPVT_output;
    }
    if (nLhs > 2) {
        retval << TAU_output;
    }
    if (nLhs > 3) {
        retval << RANK_output;
    }
    if (nLhs > 4) {
        retval << SVAL_output;
    }
    if (nLhs > 5) {
        retval << INFO_output;
    }
    return retval;
}
//=============================================================================
