# ==============================================================================
# Copyright (c) 2016-present Allan CORNET (Nelson)
# ==============================================================================
# This file is part of the Nelson.
# =============================================================================
# LICENCE_BLOCK_BEGIN
# SPDX-License-Identifier: LGPL-3.0-or-later
# LICENCE_BLOCK_END
# ==============================================================================
if(EXISTS ${CMAKE_SOURCE_DIR}/modules/modules.m)

else()
  if (WITHOUT_MEX_MODULE)
    set(WITH_MEX_MODULE "false")
  else()
    set(WITH_MEX_MODULE "true")
  endif()
  if (WITHOUT_FFTW_MODULE)
    set(WITH_FFTW_MODULE "false")
  else()
    set(WITH_FFTW_MODULE "true")
  endif()
  if (WITHOUT_SLICOT_MODULE)
    set(WITH_SLICOT_MODULE "false")
  else()
    set(WITH_SLICOT_MODULE "true")
  endif()
  if (WITHOUT_F2C_MODULE)
    set(WITH_F2C_MODULE "false")
  else()
    set(WITH_F2C_MODULE "true")
  endif()
  if (WITHOUT_MPI_MODULE)
    set(WITH_MPI_MODULE "false")
  else()
    set(WITH_MPI_MODULE "true")
  endif()
  if (WITHOUT_AUDIO_MODULE)
    set(WITH_AUDIO_MODULE "false")
  else()
    set(WITH_AUDIO_MODULE "true")
  endif()
  if (WITHOUT_WEBTOOLS_MODULE)
    set(WITH_WEBTOOLS_MODULE "false")
  else()
    set(WITH_WEBTOOLS_MODULE "true")
  endif()
  if (WITHOUT_FILE_ARCHIVER_MODULE)
    set(WITH_FILE_ARCHIVER_MODULE "false")
  else()
    set(WITH_FILE_ARCHIVER_MODULE "true")
  endif()
  if (WITHOUT_IPC_MODULE)
    set(WITH_IPC_MODULE "false")
  else()
    set(WITH_IPC_MODULE "true")
  endif()
  if (WITHOUT_PARALLEL_MODULE)
    set(WITH_PARALLEL_MODULE "false")
  else()
    set(WITH_PARALLEL_MODULE "true")
  endif()
  if (WITHOUT_GRAPHICS_MODULE)
    set(WITH_GRAPHICS_MODULE "false")
  else()
    set(WITH_GRAPHICS_MODULE "true")
  endif()
  if (WITHOUT_QML_ENGINE_MODULE)
    set(WITH_QML_ENGINE_MODULE "false")
  else()
    set(WITH_QML_ENGINE_MODULE "true")
  endif()
  if (WITHOUT_SIO_CLIENT_MODULE)
    set(WITH_SIO_CLIENT_MODULE "false")
  else()
    set(WITH_SIO_CLIENT_MODULE "true")
  endif()
  configure_file("${CMAKE_SOURCE_DIR}/modules/modules.m.in"
                 "${CMAKE_SOURCE_DIR}/modules/modules.m")
endif()
# ==============================================================================
if(EXISTS ${CMAKE_SOURCE_DIR}/modules/types/src/include/nlsConfig.h)

else()
  if (WITHOUT_MEX_MODULE)
    set(WITH_MEX_MODULE 0)
  else()
    set(WITH_MEX_MODULE 1)
  endif()
  if (WITHOUT_FFTW_MODULE)
    set(WITH_FFTW_MODULE 0)
  else()
    set(WITH_FFTW_MODULE 1)
  endif()
  if (WITHOUT_SLICOT_MODULE)
    set(WITH_SLICOT_MODULE 0)
  else()
    set(WITH_SLICOT_MODULE 1)
  endif()
  if (WITHOUT_MPI_MODULE)
    set(WITH_MPI_MODULE 0)
  else()
    set(WITH_MPI_MODULE 1)
  endif()
  if (WITHOUT_F2C_MODULE)
    set(WITH_F2C_MODULE 0)
  else()
    set(WITH_F2C_MODULE 1)
  endif()
  if (WITHOUT_AUDIO_MODULE)
    set(WITH_AUDIO_MODULE 0)
  else()
    set(WITH_AUDIO_MODULE 1)
  endif()
  if (WITHOUT_WEBTOOLS_MODULE)
    set(WITH_WEBTOOLS_MODULE 0)
  else()
    set(WITH_WEBTOOLS_MODULE 1)
  endif()
  if (WITHOUT_FILE_ARCHIVER_MODULE)
    set(WITH_FILE_ARCHIVER_MODULE 0)
  else()
    set(WITH_FILE_ARCHIVER_MODULE 1)
  endif()
  if (WITHOUT_IPC_MODULE)
    set(WITH_IPC_MODULE 0)
  else()
    set(WITH_IPC_MODULE 1)
  endif()
  if (WITHOUT_PARALLEL_MODULE)
    set(WITH_PARALLEL_MODULE 0)
  else()
    set(WITH_PARALLEL_MODULE 1)
  endif()
  if (WITHOUT_GRAPHICS_MODULE)
    set(WITH_GRAPHICS_MODULE 0)
  else()
    set(WITH_GRAPHICS_MODULE 1)
  endif()
  if (WITHOUT_QML_ENGINE_MODULE)
    set(WITH_QML_ENGINE_MODULE 0)
  else()
    set(WITH_QML_ENGINE_MODULE 1)
  endif()
  if (WITHOUT_SIO_CLIENT_MODULE)
    set(WITH_SIO_CLIENT_MODULE 0)
  else()
    set(WITH_SIO_CLIENT_MODULE 1)
  endif()
  configure_file("${CMAKE_SOURCE_DIR}/modules/types/src/include/nlsConfig.h.in"
                 "${CMAKE_SOURCE_DIR}/modules/types/src/include/nlsConfig.h")
endif()
# ==============================================================================
