# ==============================================================================
# Copyright (c) 2016-present Allan CORNET (Nelson)
# ==============================================================================
# This file is part of the Nelson.
# =============================================================================
# LICENCE_BLOCK_BEGIN
# SPDX-License-Identifier: LGPL-3.0-or-later
# LICENCE_BLOCK_END
# ==============================================================================
name: nelson
base: core22
icon: snap/gui/logo.png
summary: Let's Nelson! matrix language for engineering and scientific applications.
description: |
  Nelson is an- matrix/array programming language providing a powerful open computing environment for engineering and scientific applications using modern C/C++ libraries (Boost, Eigen, …) and others state of art numerical libraries.
  It has sophisticated data structures (including cell, struct, linear systems, …), an interpreter and a high level programming language.
  Nelson has been developed to be an open/modular system where an user can define these own data types and operations on these data types by using overload.
  Syntax is very similar to GNU Octave or MATLAB® so that most programs are easily portable.
confinement: strict
adopt-info: nelson
compression: lzo

architectures:
  - build-on: amd64

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

environment:
  XDG_RUNTIME_DIR: /tmp
  LD_LIBRARY_PATH: "$SNAP/usr/lib:$SNAP/usr/lib/x86_64-linux-gnu/:$SNAP/usr/lib/x86_64-linux-gnu/openblas-openmp:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio"
  LANG: C.UTF-8
  LC_ALL: C.UTF-8

parts:
  nelson:
    plugin: nil
    source: https://github.com/nelson-lang/nelson
    source-type: git
    source-branch: master

    override-build: |
      craftctl default

      cmake -DCMAKE_INSTALL_PREFIX=/usr  -DCMAKE_BUILD_TYPE=Release -DQTDIR=/usr/lib/qt6 -DWITHOUT_IPC_MODULE=TRUE -DWITHOUT_MPI_MODULE=TRUE . 
      cmake --build . -- -j $(nproc)
      export XDG_RUNTIME_DIR=/tmp
      cmake --build . -- -j $(nproc) buildhelp
      cmake --build . -- -j $(nproc) get_module_skeleton

      # Include the icon's path in the desktop file, not just the name.
      # This needs to happen post-build or the build versioning will show as "modified locally"
      sed -i 's|Icon=nelson|Icon=$CRAFT_PART_INSTALL/usr/share/icons/hicolor/128x128/nelson\.png|' desktop/org.nelson.Nelson.desktop

      DESTDIR=$CRAFT_PART_INSTALL cmake --build . -- install

      craftctl set grade=stable
      craftctl set version=0.7.11.0
      rm -rf $CRAFT_PART_INSTALL/usr/share/perl5/XML/
      rm -rf $CRAFT_PART_INSTALL/usr/share/texmf

    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/x86_64-linux-gnu/libc_malloc_debug.so

    build-packages:
      - build-essential
      - locales-all
      - libglvnd-dev
      - libasound2-data
      - autotools-dev
      - libtool
      - automake
      - gettext
      - pkg-config
      - libffi-dev
      - libicu-dev
      - libxml2-dev
      - libopenblas-openmp-dev
      - liblapacke-dev
      - fftw3-dev
      - libasound-dev
      - portaudio19-dev
      - libsndfile1-dev
      - libtag1-dev
      - alsa-utils
      - libslicot-dev
      - libsqlite3-dev
      - libgl1
      - hdf5-tools
      - zlib1g-dev
      - libcurl4-openssl-dev
      - libgit2-dev
      - libeigen3-dev
      - libmatio-dev
      - libboost-all-dev
      - libsqlite3-dev
      - qt6-base-dev
      - libqt6svg6
      - libqt6sql6
      - libqt6sql6-mysql
      - libqt6sql6-sqlite
      - libqt6quick6
      - libqt6opengl6-dev
      - libqt6svg6-dev
      - qt6-declarative-dev
      - qt6-documentation-tools
      - qml6-module-qtquick
      - qml6-module-qtquick-templates
      - qml6-module-qtquick-controls
      - qml6-module-qtquick-window
      - qml6-module-qtquick-dialogs
      - qml6-module-qtqml-workerscript
      - qml6-module-qtquick-layouts
      - qt6-tools-dev
      - qmlscene
      - cmake

    stage-packages:
      - libc6
      - build-essential
      - locales-all
      - libtool
      - automake
      - gettext
      - pkg-config
      - libffi7
      - libxml2
      - libopenblas0-openmp  
      - liblapacke
      - fftw3
      - libasound2-data
      - libasound2
      - libportaudio2
      - libsndfile1
      - libtag1v5
      - alsa-utils
      - libslicot0
      - libsqlite3-0
      - libgl1
      - hdf5-tools
      - zlib1g
      - libicu70
      - libcurl4
      - libgit2-1.1
      - libmatio11
      - libqt6concurrent6
      - libqt6core6
      - libqt6dbus6
      - libqt6gui6
      - libqt6network6
      - libqt6openglwidgets6
      - libqt6printsupport6
      - libqt6sql6
      - libqt6sql6-mysql
      - libqt6sql6-sqlite
      - libqt6test6
      - libqt6widgets6
      - libqt6xml6
      - qt6-qpa-plugins
      - libqt6svg6
      - libqt6quick6
      - libqt63dquick6
      - libqt6qml6
      - libqt6qmlmodels6
      - qt6-base-abi
      - libqt6quickdialogs2-6
      - libqt6quickcontrols2impl6
      - libqt6quickdialogs2-6
      - libqt6quickdialogs2quickimpl6
      - libqt6quicklayouts6
      - libqt6quickparticles6
      - qt6-documentation-tools
      - qml6-module-qtquick
      - qml6-module-qtquick-templates
      - qml6-module-qtquick-controls
      - qml6-module-qtquick-window
      - qml6-module-qtquick-dialogs
      - qml6-module-qtqml-workerscript
      - qml6-module-qtquick-layouts
      - qmlscene
      - cmake
      - libboost-chrono1.74.0
      - libboost-date-time1.74.0
      - libboost-filesystem1.74.0
      - libboost-iostreams1.74.0
      - libboost-locale1.74.0
      - libboost-regex1.74.0
      - libboost-serialization1.74.0
      - libboost-thread1.74.0

apps:
  nelson:
    command: usr/bin/nelson
    desktop: usr/share/applications/org.nelson.Nelson.desktop
    environment:
      XDG_CURRENT_DESKTOP: $XDG_CURRENT_DESKTOP:Unity:Unity7
      LD_LIBRARY_PATH: "/usr/lib/Nelson:/usr/lib:$SNAP/usr/lib/x86_64-linux-gnu/:$SNAP/usr/lib/x86_64-linux-gnu/openblas-openmp:$SNAP/usr/lib/x86_64-linux-gnu/blas:$SNAP/usr/lib/x86_64-linux-gnu/lapack:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio"
      LOCPATH: "$SNAP/usr/lib/locale"
      PATH: "$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib:$SNAP/usr/bin:$SNAP/bin:/usr/lib/x86_64-linux-gnu/qt6/bin:$PATH"
      QTDIR: "/usr/lib/x86_64-linux-gnu/qt6/"
      #QTDIR_BINARIES: "/usr/lib/x86_64-linux-gnu/qt6/bin"
      QTDIR_BINARIES: "$SNAP/usr/lib/qt6/bin/"

    plugs: &plugs
      - alsa
      - jack1
      - audio-playback
      - audio-record
      - pulseaudio
      - desktop
      - desktop-legacy
      - home
      - network
      - network-bind
      - opengl
      - removable-media
      - unity7
      - wayland
      - x11
      - browser-support
      - hardware-observe

layout:
  /usr/bin/nelson:
    bind-file: $SNAP/usr/bin/nelson
  /usr/bin/nelson_f2c:
    bind-file: $SNAP/usr/bin/nelson_f2c
  /usr/bin/nelson-cli:
    symlink: $SNAP/usr/bin/nelson-cli
  /usr/bin/nelson-adv-cli:
    symlink: $SNAP/usr/bin/nelson-adv-cli
  /usr/bin/nelson-gui:
    symlink: $SNAP/usr/bin/nelson-gui
  /usr/bin/nelson-cli-exec:
    bind-file: $SNAP/usr/bin/nelson-cli-exec
  /usr/bin/nelson-adv-cli-exec:
    bind-file: $SNAP/usr/bin/nelson-adv-cli-exec
  /usr/bin/nelson-gui-exec:
    bind-file: $SNAP/usr/bin/nelson-gui-exec
  /usr/bin/qhelpgenerator:
    bind-file: $SNAP/usr/lib/qt6/bin/qhelpgenerator


  /usr/lib/Nelson:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/Nelson

  /usr/share/Nelson:
    bind: $SNAP/usr/share/Nelson

  /usr/local/lib:
    symlink: $SNAP/usr/local/lib

  # Make staged qt plugins available in expected locations
  /usr/lib/x86_64-linux-gnu/qt6:
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/qt6

  # Make staged dri and pulseaudio modules available in expected locations
  /usr/lib/x86_64-linux-gnu/dri:
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/dri
  /usr/lib/x86_64-linux-gnu/pulseaudio:
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/pulseaudio

  # Dynamic link (used for external modules and mex)
  /usr/include:
    bind: $SNAP/usr/include
  /usr/lib/x86_64-linux-gnu/libc_nonshared.a:
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/libc_nonshared.a
  /usr/lib/x86_64-linux-gnu/libmvec_nonshared.a:
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/libmvec_nonshared.a
  /usr/lib/x86_64-linux-gnu/libpthread_nonshared.a:
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/libpthread_nonshared.a

  #alsa
  /usr/lib/x86_64-linux-gnu/alsa-lib:
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/alsa-lib
  /usr/share/alsa:
    symlink: $SNAP/usr/share/alsa
