name: Macos CI

on: [push]

jobs:

  catalina:
    name: MacOS X Catalina
    runs-on: macos-10.15
    timeout-minutes: 120    
    env:
      NELSON_VERSION: 0.5.4

    steps:
    - name: install dependencies
      run: |
        brew --version
        brew install zlib
        brew install libtool
        brew install automake
        brew unlink libffi
        brew install libffi
        brew unlink libffi
        brew link libffi --force
        brew uninstall --ignore-dependencies icu4c
        brew install icu4c
        brew unlink icu4c
        brew link icu4c --force
        brew info open-mpi
        brew install openmpi
        brew install pkg-config
        brew install pkgconfig
        brew install gettext
        brew link gettext --force
        echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.zshrc
        source ~/.zshrc
        brew install boost
        brew install libxml2
        brew upgrade cmake
        brew install qt5
        brew install fftw
        brew install portaudio
        brew install libsndfile
        brew install taglib
        brew install libgit2
        brew install hdf5
        brew install libmatio
        brew install eigen
        brew install libomp
        brew install openblas
        export BUILD_ROOT=$(pwd);
        cd /Users/runner/work/nelson;
        git clone https://github.com/Nelson-numerical-software/nelson-thirdparty-macosx.git;

    - name: Checkout
      uses: actions/checkout@v2

    - name: Update version
      run: |
        python %GITHUB_WORKSPACE%/tools/update_version/update_version.py
 
    - name: CMake
      run: |
        export PATH=/usr/local/opt/qt5/bin:$PATH
        cmake -DWITHOUT_SLICOT=TRUE -G "Unix Makefiles" .
    - name: make
      run: make -j4
    - name: get module skeleton
      run: make get_module_skeleton
    - name: build help
      run: |
        export PATH=/usr/local/opt/qt5/bin:$PATH
        make buildhelp
    - name: minimal tests
      run: make tests_minimal
    - name: package
      run: make package
    - name: all benchs
      run: make benchs_all
    - name: all tests
      run: make tests_all
    - name: Copy artifacts
      run: mkdir artifacts && mv tests_all*.* artifacts && mv benchs_all*.* artifacts && mv Nelson-*.tar.Z artifacts
    - uses: actions/upload-artifact@v1
      with:
        name: nelson-github-action-artifacts
        path: artifacts/
