name: "Prettier"

on: [push]

jobs:
  prettier_check:
    name: "Prettier - Ubuntu"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install clang-format-18
        run: |
          sudo apt-get update -q
          sudo apt-get install -y -q clang-format-18

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Check formatting
        run: |
          just format-check
